// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using CrmServices;

namespace CrmServices
{
    #region Data Context 

    public partial class CrmBoContext : DataContextBase
    {
        protected override void Configure(DataContextSettings settings)
        {
            settings.SetSchema("CrmBO");
            settings.SetDriver<SqlJsonStoreDatabaseDriver>();
            settings.MigrationsPath = @"\StoreNew\CrmBo.schema.migrations.json";

            settings.AddTable<Address>();
            settings.AddTable<Contact>();
            settings.AddTable<Person>();
        }
    }

    #endregion

    #region Entities

    public partial class Address
    { 
        public virtual int Id { get; set; }
        public virtual string Line1 { get; set; }
        public virtual string Suburb { get; set; }
        public virtual string State { get; set; }
        public virtual string PostCode { get; set; }
        public virtual string Country { get; set; }
        public virtual int PersonId { get; set; }
    }

    public partial class Contact
    { 
        public virtual int Id { get; set; }
        public virtual int PersonId { get; set; }
        public virtual string Phone { get; set; }
        public virtual string Email { get; set; }
    }

    public partial class Person
    { 
        public virtual int Id { get; set; }
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        public virtual DateTime Dob { get; set; }
    }

    #endregion
}    

