// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using Default;

namespace Default
{
    #region Data Context 

    public partial class CrmDataContext : DataContextBase
    {

    }

    #endregion

    #region Entities

    public partial class Address
    { 
        public Guid Id { get; set; }
        public string Line1 { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public bool Deleted { get; set; }
    }

    public partial class Person
    { 
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public DateTime? Dob { get; set; }
    }

    #endregion
}    

