// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using Default;

namespace Default
{
    #region Data Context 

    public partial class CrmDataContext : DataContextBase
    {
        protected override void Configure(TableCollection tables)
        {
            tables.Add<Address>();
            tables.Add<Person>();
        }
    }

    #endregion

    #region Entities

    public partial class Address
    { 
        public virtual long Id { get; set; }
        public virtual string Line1 { get; set; }
        public virtual string Suburb { get; set; }
        public virtual string City { get; set; }
        public virtual string PostCode { get; set; }
        public virtual bool Deleted { get; set; }
    }

    public partial class Person
    { 
        public virtual long Id { get; set; }
        public virtual string Name { get; set; }
        public virtual string Surname { get; set; }
        public virtual string Phone { get; set; }
        public virtual DateTime? Dob { get; set; }
    }

    #endregion
}    

