// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using MasterDetailsDataEntry.Demo.Database;

namespace Default
{
    #region Interface 

    public partial interface IMyDataService
    {
        List<CustAddrCount> GetCustAddrCountList(QueryOptions options, params object[] parameters);
        List<CustAddrSubQuery> GetCustAddrSubQueryList(QueryOptions options, params object[] parameters);
        List<Cust> GetCustList(QueryOptions options, params object[] parameters);
        List<CustomerAddress> GetCustomerAddressList(QueryOptions options, params object[] parameters);
        List<ProdModel> GetProdModelList(QueryOptions options, params object[] parameters);
        List<WeightByCost> GetWeightByCostList(QueryOptions options, params object[] parameters);
    }

    #endregion

    #region Data Service 

    public partial class MyDataService : DataServiceBase<AdventureWorksContext>, IMyDataService
    {
        public List<CustAddrCount> GetCustAddrCountList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetCustAddrCountListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<CustAddrCount> GetCustAddrCountListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            
            var Query1 =
                from c in db.CustomerAddress
                group new { c } by new { c.CustomerId } into group1
                where group1.Count() > 1
                select new 
                { 
                    CustomerId = group1.Key.CustomerId, 
                    AddrCount = group1.Count(), 
                };
            
                var query =
                    from c in db.Customer
                    join q in Query1 on c.CustomerId equals q.CustomerId
                    select new CustAddrCount
                    { 
                        CustomerId = c.CustomerId, 
                        CompanyName = c.CompanyName, 
                        EmailAddress = c.EmailAddress, 
                        FirstName = c.FirstName, 
                        LastName = c.LastName, 
                        MiddleName = c.MiddleName, 
                        ModifiedDate = c.ModifiedDate, 
                        NameStyle = c.NameStyle, 
                        PasswordHash = c.PasswordHash, 
                        PasswordSalt = c.PasswordSalt, 
                        Phone = c.Phone, 
                        Rowguid = c.Rowguid, 
                        SalesPerson = c.SalesPerson, 
                        Suffix = c.Suffix, 
                        Title = c.Title, 
                        AddrCount = q.AddrCount, 
                    };

            return query;
        }

        public List<CustAddrSubQuery> GetCustAddrSubQueryList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetCustAddrSubQueryListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<CustAddrSubQuery> GetCustAddrSubQueryListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            
                var Query2 =
                    from c in db.CustomerAddress
                    select new 
                    { 
                        CustomerId = c.CustomerId, 
                        AddressId = c.AddressId, 
                        type = c.AddressType, 
                        ModifiedDate = c.ModifiedDate, 
                    };
            
                var Query1 =
                    from q in Query2
                    select new 
                    { 
                        CustomerId = q.CustomerId, 
                        AddressId = q.AddressId, 
                        type2 = q.type, 
                        ModifiedDate = q.ModifiedDate, 
                    };
            
                var query =
                    from c in db.Customer
                    join q in Query1 on c.CustomerId equals q.CustomerId
                    select new CustAddrSubQuery
                    { 
                        CustomerId = q.CustomerId, 
                        AddressId = q.AddressId, 
                        type2 = q.type2, 
                        ModifiedDate = q.ModifiedDate, 
                        CompanyName = c.CompanyName, 
                        EmailAddress = c.EmailAddress, 
                        FirstName = c.FirstName, 
                        LastName = c.LastName, 
                        MiddleName = c.MiddleName, 
                        NameStyle = c.NameStyle, 
                        PasswordHash = c.PasswordHash, 
                        PasswordSalt = c.PasswordSalt, 
                        Phone = c.Phone, 
                        Rowguid = c.Rowguid, 
                        SalesPerson = c.SalesPerson, 
                        Suffix = c.Suffix, 
                        Title = c.Title, 
                    };

            return query;
        }

        public List<Cust> GetCustList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetCustListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<Cust> GetCustListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            var name = (String)parameters[0];

            
                var query =
                    from c in db.Customer
                    where c.FirstName == name
                    select new Cust
                    { 
                        CustomerId = c.CustomerId, 
                        CompanyName = c.CompanyName, 
                        EmailAddress = c.EmailAddress, 
                        FirstName = c.FirstName, 
                        LastName = c.LastName, 
                        MiddleName = c.MiddleName, 
                        ModifiedDate = c.ModifiedDate, 
                        NameStyle = c.NameStyle, 
                        PasswordHash = c.PasswordHash, 
                        PasswordSalt = c.PasswordSalt, 
                        Phone = c.Phone, 
                        Rowguid = c.Rowguid, 
                        SalesPerson = c.SalesPerson, 
                        Suffix = c.Suffix, 
                        Title = c.Title, 
                    };

            return query;
        }

        public List<CustomerAddress> GetCustomerAddressList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetCustomerAddressListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<CustomerAddress> GetCustomerAddressListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            var p1 = (Int32)parameters[0];

            
                var query =
                    from cu in db.Customer
                    join c in db.CustomerAddress on cu.CustomerId equals c.CustomerId
                    join a in db.Address on c.AddressId equals a.AddressId
                    where c.CustomerId == p1
                    select new CustomerAddress
                    { 
                        AddressId = a.AddressId, 
                        AddressLine1 = a.AddressLine1, 
                        AddressLine2 = a.AddressLine2, 
                        City = a.City, 
                        CountryRegion = a.CountryRegion, 
                        ModifiedDate = a.ModifiedDate, 
                        PostalCode = a.PostalCode, 
                        Rowguid = a.Rowguid, 
                        StateProvince = a.StateProvince, 
                        CustomerId = c.CustomerId, 
                        AddressType = c.AddressType, 
                        Title = cu.Title, 
                        FirstName = cu.FirstName, 
                        LastName = cu.LastName, 
                    };

            return query;
        }

        public List<ProdModel> GetProdModelList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetProdModelListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<ProdModel> GetProdModelListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            
            var query =
                from p in db.ProductModel
                group new { p } by new { p.ProductModelId, p.CatalogDescription, p.Name } into group1
                select new ProdModel
                { 
                    ProductModelId = group1.Key.ProductModelId, 
                    CatalogDescription = group1.Key.CatalogDescription, 
                    Name = group1.Key.Name, 
                };

            return query;
        }

        public List<WeightByCost> GetWeightByCostList(QueryOptions options, params object[] parameters)
        {
            using (var db = GetDbContext())
            {
                var query = GetWeightByCostListQuery(db, options, parameters);
                query = Prepare(query, options, parameters);
                var result = query.ToList();
                return result;
            }
        }

        public IQueryable<WeightByCost> GetWeightByCostListQuery(AdventureWorksContext db, QueryOptions options, params object[] parameters)
        {
            
            var query =
                from p in db.Product
                where p.Weight > 100
                group new { p } by new { p.StandardCost } into group1
                where group1.Count() > 1 && group1.Min(x => x.p.Name) == "Agata"
                select new WeightByCost
                { 
                    Count = group1.Count(), 
                    StandardCost = group1.Key.StandardCost, 
                    Name = group1.Min(x => x.p.Name), 
                };

            return query;
        }

    }

    #endregion

    #region Entities

    public partial class CustAddrCount
    {
        public Int32 CustomerId { get; set; }
        public String CompanyName { get; set; }
        public String EmailAddress { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String MiddleName { get; set; }
        public DateTime ModifiedDate { get; set; }
        public Boolean NameStyle { get; set; }
        public String PasswordHash { get; set; }
        public String PasswordSalt { get; set; }
        public String Phone { get; set; }
        public Guid Rowguid { get; set; }
        public String SalesPerson { get; set; }
        public String Suffix { get; set; }
        public String Title { get; set; }
        public Int32 AddrCount { get; set; }
    }

    public partial class CustAddrSubQuery
    {
        public Int32 CustomerId { get; set; }
        public Int32 AddressId { get; set; }
        public String type2 { get; set; }
        public DateTime ModifiedDate { get; set; }
        public String CompanyName { get; set; }
        public String EmailAddress { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String MiddleName { get; set; }
        public Boolean NameStyle { get; set; }
        public String PasswordHash { get; set; }
        public String PasswordSalt { get; set; }
        public String Phone { get; set; }
        public Guid Rowguid { get; set; }
        public String SalesPerson { get; set; }
        public String Suffix { get; set; }
        public String Title { get; set; }
    }

    public partial class Cust
    {
        public Int32 CustomerId { get; set; }
        public String CompanyName { get; set; }
        public String EmailAddress { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String MiddleName { get; set; }
        public DateTime ModifiedDate { get; set; }
        public Boolean NameStyle { get; set; }
        public String PasswordHash { get; set; }
        public String PasswordSalt { get; set; }
        public String Phone { get; set; }
        public Guid Rowguid { get; set; }
        public String SalesPerson { get; set; }
        public String Suffix { get; set; }
        public String Title { get; set; }
    }

    public partial class CustomerAddress
    {
        public Int32 AddressId { get; set; }
        public String AddressLine1 { get; set; }
        public String AddressLine2 { get; set; }
        public String City { get; set; }
        public String CountryRegion { get; set; }
        public DateTime ModifiedDate { get; set; }
        public String PostalCode { get; set; }
        public Guid Rowguid { get; set; }
        public String StateProvince { get; set; }
        public Int32 CustomerId { get; set; }
        public String AddressType { get; set; }
        public String Title { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
    }

    public partial class ProdModel
    {
        public Int32 ProductModelId { get; set; }
        public String CatalogDescription { get; set; }
        public String Name { get; set; }
    }

    public partial class WeightByCost
    {
        public Int32 Count { get; set; }
        public Decimal StandardCost { get; set; }
        public String Name { get; set; }
    }

    #endregion
}
