// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using Default;

namespace Default.StoreNew
{
    #region Interface 

    public partial interface ICrm2DataService
    {
        List<PersonAddress> GetPersonAddressList(params object[] parameters);
    }

    #endregion

    #region Data Service 

    public partial class Crm2DataService : StoreDataServiceBase<CrmDataContext>, ICrm2DataService
    {
        public List<PersonAddress> GetPersonAddressList(params object[] parameters)
        {
            var p1 = (int)parameters[0];

            using (var db = GetDbContext())
            {
                var query =
                    from a in db.Address 
                    join p in db.PersonAddress on a.Id equals p.AddressId
                    join pe in db.Person on p.PersonId equals pe.Id
                    where ((a.Deleted == 0) && (p.Deleted == 0)) && (pe.Id == p1)
                    select new PersonAddress
                    {
                        Id = a.Id,
                        Line1 = a.Line1,
                        Suburb = a.Suburb,
                        State = a.State,
                        PostCode = a.PostCode,
                        Country = a.Country,
                        PersonId = p.PersonId,
                        AddressId = p.AddressId,
                        Name = pe.Name,
                        Surname = pe.Surname,
                        Phone = pe.Phone,
                        Dob = pe.Dob,
                        Id = pe.Id,
                    };

                var result = query.ToList();
                return result;
            }
        }

    }

    #endregion

    #region Entities

    public partial class PersonAddress
    {
        public int AddrId { get; set; }
        public string Line1 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public int? PersonId { get; set; }
        public int? AddressId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public DateTime? Dob { get; set; }
        public int Id { get; set; }
    }

    #endregion
}
