// *******************************************************************************************************
// This code is auto generated by Platz.ObjectBuilder template, any changes made to this code will be lost
// *******************************************************************************************************
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using Platz.ObjectBuilder;
using Platz.SqlForms;
using Default;

namespace Default.StoreNew
{
    #region Interface 

    public partial interface ICrm2DataService
    {
        List<PersonAddress> GetPersonAddressList(params object[] parameters);
    }

    #endregion

    #region Data Service 

    public partial class Crm2DataService : StoreDataServiceBase<CrmDataContext>, ICrm2DataService
    {
        public List<PersonAddress> GetPersonAddressList(params object[] parameters)
        {
            var sql = @$"
SELECT
      a.Id AS AddrId
    , JSON_VALUE(a.data, '$.Line1') AS Line1
    , JSON_VALUE(a.data, '$.Suburb') AS Suburb
    , JSON_VALUE(a.data, '$.State') AS State
    , JSON_VALUE(a.data, '$.PostCode') AS PostCode
    , JSON_VALUE(a.data, '$.Country') AS Country
    , p.PersonId AS PersonId
    , p.AddressId AS AddressId
    , JSON_VALUE(pe.data, '$.Name') AS Name
    , JSON_VALUE(pe.data, '$.Surname') AS Surname
    , JSON_VALUE(pe.data, '$.Phone') AS Phone
    , CAST(JSON_VALUE(pe.data, '$.Dob') AS DATE2) AS Dob
    , pe.Id AS Id
FROM Address a
INNER JOIN PersonAddress p ON a.Id = p.AddressId
INNER JOIN Person pe ON p.PersonId = pe.Id
WHERE ((a.Deleted = 0) AND (p.Deleted = 0)) AND (pe.Id = @p1)
";
            using var db = GetDbContext();
            var result = db.ExecuteQuery<PersonAddress>(sql, parameters);
            return result;
        }

    }

    #endregion

    #region Entities

    public partial class PersonAddress
    {
        public int AddrId { get; set; }
        public string Line1 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public int? PersonId { get; set; }
        public int? AddressId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public DateTime? Dob { get; set; }
        public int Id { get; set; }
    }

    #endregion
}
